name: test
networks:
- name: default
resource_pools:
- name: rp
jobs:
- name: job1
  template: xyz
  networks:
  - name: default
- name: new_job
  template: changed_templated_causing_failure
  networks:
  - name: default