#!/bin/bash

RUN_DIR=/var/vcap/sys/run/blobstore
LOG_DIR=/var/vcap/sys/log/blobstore
PIDFILE=$RUN_DIR/nginx.pid

DATA=/var/vcap/store/blobstore
TMP_DIR=$DATA/tmp/uploads

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $TMP_DIR
  	chown -R vcap:vcap $RUN_DIR $LOG_DIR $DATA

    echo $$ > $PIDFILE

    exec /var/vcap/packages/nginx/sbin/nginx -c /var/vcap/jobs/blobstore/config/nginx.conf >>$LOG_DIR/nginx.stdout.log 2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)

    CHILD_PIDS=`pgrep -P ${PID}`
    kill -9 ${PID}
    [ ! -z "$CHILD_PIDS" ] && for pid in $CHILD_PIDS ; do kill -9 $pid ; done

    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: nginx_ctl {start|stop}" ;;
esac
exit 0
