#!/bin/bash

RUN_DIR=/var/vcap/sys/run/redis
LOG_DIR=/var/vcap/sys/log/redis
STORE=/var/vcap/store/redis
PIDFILE=$RUN_DIR/redis.pid
RUNAS=vcap

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $STORE
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $STORE

    echo $$ > $PIDFILE

    exec chpst -u $RUNAS:$RUNAS \
      /var/vcap/packages/redis/bin/redis-server \
      /var/vcap/jobs/redis/config/redis.conf \
      >>$LOG_DIR/redis.stdout.log \
      2>>$LOG_DIR/redis.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    CHILD_PIDS=`pgrep -P ${PID}`
    kill -9 ${PID}
    [ ! -z "$CHILD_PIDS" ] && for pid in $CHILD_PIDS ; do kill -9 $pid ; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: redis_ctl {start|stop}" ;;
esac
exit 0
