#!/bin/bash

LOG_DIR=/var/vcap/sys/log/nagios

case $1 in

  start)
       touch /var/vcap/sys/log/nagios/ngraph.log
       chown vcap /var/vcap/sys/log/nagios/ngraph.log
       /var/vcap/jobs/nagios_dashboard/bin/nagios_grapher start >>$LOG_DIR/nagios_grapher.stdout.log 2>>$LOG_DIR/nagios_grapher.stderr.log
    ;;

  stop)
        /var/vcap/jobs/nagios_dashboard/bin/nagios_grapher stop
    ;;

  *)
    echo "Usage: nagios_ctl {start|stop}"

    ;;

esac
