---
ruby/bundler-1.1.5.gem:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E2MWUxMjEyMDRlNGU4NmVlYmU1OTEwNTA1MThh%0AODNiNmQzZSIsInNpZyI6IkZCKy9NU2dzaW5KRmFrY1g2THY2ckF6UEtpZz0i%0AfQ==%0A
  sha: de1b94c25350a350457d2768e081c5be4217f087
  size: 205312
ruby/rake-0.9.2.2.gem:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2EyMWUxMjIwMDRlNGU4ZWM2NDdhNTQwNTA1MThh%0AOGE1OWVkZCIsInNpZyI6IlZWMTdPeUhjcTE0ZUpMc1QvM1NvTElldW41WT0i%0AfQ==%0A
  sha: 5372835ce532b7a06e437c83bc7a4938cb48c0d1
  size: 111616
ruby/ruby-1.9.2-p320.tar.gz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2E0MWUxMjIyMDRlNGU5ODYzZDA3NjMwNTA1MThh%0AYWU3MjM2NCIsInNpZyI6Ik9MZ2Q5aW5vZU1tNUkwaHlVaHJVUy9oNHN3az0i%0AfQ==%0A
  sha: ead282bf780eb671a627e5e071f96c2fa4c64c1a
  size: 11338691
ruby/rubygems-1.8.24.tgz:
  object_id: eyJvaWQiOiI0ZTRlNzhiY2ExMWUxMjEwMDRlNGU3ZDUxMWY4MjEwNTA1MThi%0AMGM5NWUzNyIsInNpZyI6IkMxaEs5TDZKNDA0L2IzVVpUN014OXB1RmFCOD0i%0AfQ==%0A
  sha: 30f27047e74f7943117736a0d3e224994fee0905
  size: 380101
